'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NavBarResponsive.Shared


	Partial Public Class SideBar
		Inherits UserControl

		''' <summary>
		''' navTreeView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected navTreeView As Global.DevExpress.Web.Bootstrap.BootstrapTreeView
	End Class
End Namespace
