'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NavBarResponsive


	Partial Public Class SiteMaster
		Inherits MasterPage

		''' <summary>
		''' SideBar control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SideBar As Global.NavBarResponsive.Shared.SideBar

		''' <summary>
		''' Content control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Content As System.Web.UI.WebControls.ContentPlaceHolder
	End Class
End Namespace
