'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace NavBarResponsive


	Partial Public Class GridView
		Inherits System.Web.UI.Page

		''' <summary>
		''' BootstrapGridView1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected BootstrapGridView1 As Global.DevExpress.Web.Bootstrap.BootstrapGridView

		''' <summary>
		''' ObjectDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ObjectDataSource1 As System.Web.UI.WebControls.ObjectDataSource
	End Class
End Namespace
